# FROM rabbitmq:4
# ENV RABBITMQ_DEFAULT_USER="roboshop" \
#     RABBITMQ_DEFAULT_PASS="roboshop123" \

 FROM rabbitmq:4.0.9-alpine
 ENV RABBITMQ_DEFAULT_USER="roboshop" \
     RABBITMQ_DEFAULT_PASS="roboshop123" \